version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/local/Dockerfile
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
    ports:
      - "9000"   # 内部ネットワークで php-fpm ポートを公開
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_ucrm
      MYSQL_USER: laravel_ucrm
      MYSQL_PASSWORD: password123
      TZ: 'Asia/Tokyo'
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "3001:80"
 
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    container_name: nginx-server
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  db_data:
