on: [push]

name: Linux_Container_Node_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@main

    - name: 'Sign in via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - uses: azure/docker-login@v1
      with:
        login-server: azuredeployrunnerregi.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t azuredeployrunnerregi.azurecr.io/laravel_ucrm_app:${{ github.sha }}
        docker push azuredeployrunnerregi.azurecr.io/laravel_ucrm_app:${{ github.sha }}     

    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'laravel-deploy-test'
        images: 'azuredeployrunnerregi.azurecr.io/laravel_ucrm_app:${{ github.sha }}'

    - name: Azure logout
      run: |
        az logout
